config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "search" => "searches#search"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  
  end  
  resources :animals do
   resources :animal_comments, only: [:create, :destroy,]
   resource :favorites, only: [:create, :destroy]
  end


end

app/models/animal.rb
class Animal < ApplicationRecord

  belongs_to :user
  has_many :animal_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no-image.png')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

   with_options presence: true do
    validates :title
    validates :body
    validates :profile_image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @animal = Animal.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @animal = Animal.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @animal = Animal.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @animal = Animal.where("title LIKE?","%#{word}%")
    else
      @animal = Animal.all
    end
  end


end

app/models/animal_comment.rb
class AnimalComment < ApplicationRecord
  belongs_to :user
  belongs_to :animal

  validates :comment, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :animal

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals, dependent: :destroy
  has_many :animal_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy


 def  follow(user_id)
  relationships.create(followed_id: user_id)
 end

 def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
 end

 def following?(user)
   followings.include?(user)
 end

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no-image.png')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :username, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("username LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("username LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("username LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("username LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end


end

app/controllers/animal_comments_controller.rb
class AnimalCommentsController < ApplicationController

  def create
    animal = Animal.find(params[:animal_id])
    comment = current_user.animal_comments.new(animal_comment_params)
    comment.animal_id = animal.id
    comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    AnimalComment.find(params[:id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def animal_comment_params
    params.require(:animal_comment).permit(:comment)
  end

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @animals = Animal.all

  end

  def show
    @animal = Animal.find(params[:id])
    @animal_comment = AnimalComment.new
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id
    if @animal.save
    redirect_to animal_path(@animal), notice: "紹介に成功しました"
    else
    render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    if @animal.user != current_user
    redirect_to animals_path, alert: "不正なアクセスです"
    end
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
    redirect_to animal_path(@animal), notice: "更新に成功しました"
    else
    render :edit
    end
  end

  def destroy
    animal = Animal.find(params[:id])
    animal.destroy
    redirect_to animals_path
  end


  private

  def animal_params
    params.require(:animal).permit(:title, :body, :profile_image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    animal = Animal.find(params[:animal_id])
    favorite = current_user.favorites.new(animal_id: animal.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    animal = Animal.find(params[:animal_id])
    favorite = current_user.favorites.find_by(animal_id: animal.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
 
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer  
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
  @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @animals = Animal.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @animal = Animal.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user), notice: "更新に成功しました"
    else
    render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

end

app/helpers/animal_comments_helper.rb
module AnimalCommentsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/animals/_favorite.html.erb
 <% if animal.favorited_by?(current_user) %>
    <p>
      <%= link_to animal_favorites_path(animal), method: :delete , class: "text-danger" do %>
        <i class="fas fa-heart"></i><%= animal.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to animal_favorites_path(animal), method: :post , class: "text-info" do %>
        <i class="far fa-heart"></i><%= animal.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

app/views/animals/edit.html.erb
<% if @animal.errors.any? %>
   <div class="alert alert-danger">
    <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @animal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="containar">
   <h3 class="p-3 bg-danger  text-center  text-white">-Pet Edit-</h3>
   <div class="row no-gutters">
   <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light py-4 mb-0">ペット紹介編集</h5>
        <div class="form-body p-4">
          <%= form_with model: @animal, local: true do |f| %>

          <div class="text-left">
            <%= f.label :ペット名 %>
            <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputName", placeholder:"ペット名"%>
          </div>

          <div class="text-left">
          <%= f.label :ペット紹介 %>
          <%= f.text_area :body,autofocus: true, class: "form-control", placeholder: "ペット紹介" %>
          </div>
          <div class="text-left">
          <%= f.label :ペット紹介画像 %><br>
          <%= f.file_field :profile_image, accept: "image/" %>
          </div>
          <%= f.submit "変更する" , class: "btn btn-outline-success" %>


   <% end %>

      </div>
    </div>
  </div>
</div>

app/views/animals/index.html.erb
<h3 class="p-3 bg-danger  text-center  text-white">-Navigator Index-</h3>
<div class="card-group mb-3">

  <% @animals.each do |animal| %>
  <div class="card" style="width: 18rem">

    <%= link_to animal_path(animal) do %>
    <%= image_tag animal.get_profile_image(300,300), class:"card-img-top";%>
    <% end %>

    <div class="card-body">
     <h5 class="card-title"><%= link_to animal.title ,animal_path(animal)%></h5>
     <%= link_to user_path(animal.user.id) do %>
     <%= image_tag animal.user.get_profile_image(100,100), class:"mt-3 rounded-circle";  %>
     <% end %>
     <%= render 'favorite', animal: animal %>
     <time><%= animal.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
    </div>
  </div>
    <% end %>

app/views/animals/new.html.erb
<% if @animal.errors.any? %>
  <div class="alert alert-danger">
    <h2><%= pluralize(@animal.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @animal.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="containar">
   <h3 class="p-3 bg-danger  text-center  text-white">-Pets Introduction-</h3>
   <div class="row no-gutters">
   <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light py-4 mb-0">ペット紹介ページ</h5>
        <div class="form-body p-4">
          <%= form_with model: @animal, local: true do |f| %>

          <div class="text-left">
            <%= f.label :ペット名 %>
            <%= f.text_field :title, autofocus: true, class:"form-control", id:"inputName", placeholder:"ペット名"%>
          </div>

          <div class="text-left">
            <%= f.label :ペット紹介 %>
            <%= f.text_area :body,autofocus: true, class: "form-control", placeholder: "ペット紹介" %>
          </div>
          <div class="text-left">
            <%= f.label :ペット紹介画像 %><br>
            <%= f.file_field :profile_image, accept: "image/" %>
          </div>
          <%= f.submit "紹介する" , class: "btn btn-outline-success" %>


   <% end %>

      </div>
    </div>
  </div>
</div>

app/views/animals/show.html.erb
<h3 class="p-3 bg-danger  text-center  text-white">-Pet Nave-</h3>
　<div class="card-list-containar py-5">

    <div class="card w-50 mx-auto  shadow-lg">

        <%= image_tag @animal.get_profile_image(300,300), class:"card-img-top"; %>
        <div class="card-body">
          <div class="row">
            <div class="col-10">
              <strong>
              <p class="card-title">

              <%= @animal.title %>
              </p>
              <p class="card-txet">Pet紹介

              <%= simple_format @animal.body %>
              </p>
              <p>コメント件数：<%= @animal.animal_comments.count %></p>
              <%= render 'favorite', animal: @animal %>
              </strong>
             
              <div>
                <% @animal.animal_comments.each do |animal_comment| %>
                  <div class="card-header">
                     <%= image_tag animal_comment.user.get_profile_image(100,100) %>
                     <%= animal_comment.user.username %><br>
                     <time><%= animal_comment.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
                  </div>
                  <div class="card-body">
                    <%= animal_comment.comment %>
                  </div>
                  <div class="card-footer">
                    <% if animal_comment.user == current_user %>
                    <%= link_to "コメントを削除する", animal_animal_comment_path(animal_comment.animal, animal_comment), method: :delete , class: "btn btn-outline-primary"%>
                    <% end %>
                  </div>
                <% end %>
              </div>
              <div>
                <%= form_with model: [@animal, @animal_comment] do |f| %>
                <%= f.text_area :comment, rows: '5', placeholder: "お気軽にコメントをどうぞ" ,class: "form-control "%>
                <%= f.submit "コメントを送信する" ,class: "my-2  btn btn-outline-info" %>
                <% end %>
              </div>
                <% if @animal.user.id == current_user.id %>
                <%= link_to "編集する" , edit_animal_path(@animal) ,class: "btn btn-outline-success"%>
                <% end %>
             </div>
          </div>
      </div>
   </div>
</div>

app/views/home/index.html.erb
 <div class="container  mt-5">
    <div class="row text-center ">
      <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6 ">
        <h1><strong><i class="fas fa-paw"></i> Animal Nav</strong></h1>
              <div class="btn-wrapper col-10 mx-auto">
                <div class="row  mt-4">
                  <%= link_to "Log in", new_user_session_path , class: "btn btn-danger btn-sm btn-block mb-3 sign_in" %><br>
                </div>
                <div class="row">
                <%= link_to "Sign up", new_user_registration_path , class: "btn btn-danger btn-sm btn-block sign_up" %>
                </div>
            </div>
      </div>
    </div>
</div>

app/views/relationships/_follow.html.erb
<table class='table'>
   <thead>
     <tr>
      <th>プロフィール画像</th>
      <th>名前</th>
      <th>自己紹介</th>
      <th colspan="3"></th>
    </tr>
</thead>
<tbody>
  <% if users.exists? %>
  <% users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(200,200), class:"mt-3 rounded-circle"; %></td>
      <td><%= user.username %></td>
      <td><%= user.profile %></td>
    </tr>
</tbody>
<% end %>

<% else %>
<p>ユーザーはいません</p>
<% end %>
</table>

app/views/relationships/followers.html.erb
   <h3 class="p-3 bg-danger  text-center  text-white">-Follow-</h3>
     <%= render 'follow', users: @users %>   
 

app/views/relationships/followings.html.erb
   <h3 class="p-3 bg-danger  text-center  text-white">-Follow-</h3>
     <%= render 'follow', users: @users %>   
 

app/views/searches/search.html.erb
<h3 class="p-3 bg-danger  text-center  text-white">-Search Results-</h3>
<table class='table'>
   <% if @range == "User" %>
   <thead>
     <tr>
      <th>プロフィール画像</th>
      <th>名前</th>
      <th>自己紹介</th>
      <th colspan="3"></th>
    </tr>
</thead>
<tbody>
  <% @users.each do |user| %>
    <tr>
      <td><%= image_tag user.get_profile_image(200,200), class:"mt-3 rounded-circle"; %></td>
      <td><%= user.username %></td>
      <td><%= user.profile %></td>
    </tr>
  <% end %>
</tbody>
  <% else %>
<thead>
    <tr>
      <th>プロフィール画像</th>
      <th>名前</th>
      <th>自己紹介</th>
      <th colspan="3"></th>
    </tr>
</thead>
<tbody>
    <tbody>
      <% @animals.each do |animal| %>
        <tr>
          <td><%= image_tag animal.get_profile_image(200,200), class:"mt-3 rounded-circle"; %></td>
          <td><%= animal.title %></td>
          <td><%= animal.body %></td>
        </tr>
      <% end %>
    </tbody>
  <% end %>
</table>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
   <div class="alert alert-danger">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this object from being saved: not successfully</h2>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<div class="containar">
   <h3 class="p-3 bg-danger  text-center  text-white">-Navigator Edit-</h3>
   <div class="row no-gutters">
   <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light py-4 mb-0">プロフィール編集</h5>
        <div class="form-body p-4">
          <%= form_with model: @user, local: true do |f| %>

          <div class="text-left">
            <%= f.label :ユーザー名 %>
            <%= f.text_field :username, autofocus: true, class:"form-control", id:"inputName", placeholder:"名前"%>
          </div>
          <div class="text-left">
            <%= f.label :メールアドレス %>
            <%= f.text_field :email,autofocus: true, class: 'form-control', placeholder: 'メールアドレス *', id: 'email'  %>
          </div>
          <div class="text-left">
            <%= f.label :プロフィール %>
            <%= f.text_area :profile,autofocus: true, class: "form-control", placeholder: "プロフィール" %>
          </div>
          <div class="text-left">
            <%= f.label :プロフィール画像 %><br>
            <%= f.file_field :profile_image, accept: "image/" %>
          </div>
          <%= f.submit "変更する" , class: "btn btn-outline-success" %>


         <% end %>

      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h3 class="p-3 bg-danger  text-center  text-white">-Navigator Index-</h3>
<div class="card-group mb-3">

  <% @users.each do |user| %>
  <div class="card" style="width: 18rem">
    <%= link_to user_path(user) do %>
    <%= image_tag user.get_profile_image(300,300), class:"card-img-top";%>
    <% end %>
    <div class="card-body">
     <h5 class="card-title"><%= link_to user.username ,user_path(user)%></h5>
     <p>投稿数:<%= user.animals.count %></p>
     <p>コメント件数：<%= user.animal_comments.count %></p>
     <p><%= link_to user_followings_path(user) do %></p>
     <p>Follow: <%= user.followings.count %></p>
     <% end %>
     <p><%= link_to user_followers_path(user) do %></p>
     <p>Follower: <%= user.followers.count %></p>
     <% end %>
     <% if user.id != current_user.id %>
     <% if current_user.following?(user) %>
      <p><%= link_to  user_relationships_path(user.id), method: :delete , class: "text-danger" do %></p>
      <i class="fab fa-twitter-square"></i> フォロー外す<% end %>
     <% else %>
      <p><%= link_to  user_relationships_path(user.id), method: :post , class: "text-info" do %></p>
      <i class="fab fa-twitter-square"></i>  フォローする<% end %>
     <% end %>
     <% end %>
    <%= link_to  "Navigator" ,user_path(user) , class: "btn btn-outline-info"%>
    </div>
  </div>
    <% end %>
 </div>

app/views/users/show.html.erb
<div class="containar">
   <h3 class="p-3 bg-danger  text-center  text-white">-Navigator-</h3>
     <table class="table  table-light  ">
       <tr>
         <thed>
           <tr>
             <th>プロフィール画像</th>
             <th>名前</th>
             <th>自己紹介</th>
             <% if @user.id != current_user.id %>
             <th><% if current_user.following?(@user) %>
             <%= link_to  user_relationships_path(@user.id), method: :delete , class: "text-danger" do %>
               <i class="fab fa-twitter-square"></i></td> フォロー外す<% end %>
             <% else %>
             <%= link_to  user_relationships_path(@user.id), method: :post , class: "text-info" do %>
               <i class="fab fa-twitter-square"></i></td>  フォローする<% end %>
             <% end %>
             <% end %></th>
           </tr>
         </thed>
         <td><%= image_tag @user.get_profile_image(200,200), class:"mt-3 rounded-circle"; %></td>
         <td><%= @user.username %></td>
         <td><%= @user.profile %></td>
         <td><% if @user.id == current_user.id %>
         <td><%= @user.email %></td>
         <td> <%= link_to "プロフィール編集" , edit_user_path(@user) , class: "btn btn-outline-info"%></td>
         <% end %>
        </tr>
     </table>
</div>
<div class="containar">
  <div class="row">
    <div class="card-group mb-3">
      <% @user.animals.each do |animal| %>
      <div class="card border-dark mb-3 " style="width: 18rem;">

        <%= image_tag animal.get_profile_image(200,200), class: "card-img-top"%>

          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              <%= link_to animal_path(animal),class: "font-weight-bold   text-secondary " do %>
           <i class="fas fa-cookie-bite"></i>  <%= animal.title %>を見に行く<% end %>
            </li>
            <% if @user.id == current_user.id %>
            <li class="list-group-item">
              <%= link_to edit_animal_path(animal),class: "font-weight-bold  text-secondary "  do %>
              <i class="fas fa-edit"></i> <%= animal.title %>の情報を編集する
              <% end %>
            </li>
            <li class="list-group-item">
              <%= link_to animal_path(animal), method: :delete, data: {confirm: "本当にさよならしますか？"} ,class: "font-weight-bold  text-secondary " do %>
              <i class="fas fa-ghost"></i> <%= animal.title %>と本当にさよならしますか?<% end %>
            </li>
            <% end %>
            <li class="list-group-item">
             <time><%= animal.updated_at.strftime("%Y-%m-%d %H:%M") %></time>更新
            </li>
          </ul>
      </div>
      <% end %>
    </div>
  </div>
</div>