config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get "search" => "searches#search"
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  
  end  
  resources :animals do
   resources :animal_comments, only: [:create, :destroy,]
   resource :favorites, only: [:create, :destroy]
  end


end

app/models/animal.rb
class Animal < ApplicationRecord

  belongs_to :user
  has_many :animal_comments, dependent: :destroy

  has_many :favorites, dependent: :destroy


  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no-image.png')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

   with_options presence: true do
    validates :title
    validates :body
    validates :profile_image
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @animal = Animal.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @animal = Animal.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @animal = Animal.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @animal = Animal.where("title LIKE?","%#{word}%")
    else
      @animal = Animal.all
    end
  end


end

app/models/animal_comment.rb
class AnimalComment < ApplicationRecord
  belongs_to :user
  belongs_to :animal

  validates :comment, presence: true

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :animal

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :animals, dependent: :destroy
  has_many :animal_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy


  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy


 def  follow(user_id)
  relationships.create(followed_id: user_id)
 end

 def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
 end

 def following?(user)
   followings.include?(user)
 end

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  def get_profile_image(width, height)
  unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/no-image.png')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  end
  profile_image.variant(resize_to_limit: [width, height]).processed
  end

  validates :username, presence: true

  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("username LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("username LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("username LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("username LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end


end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @animals = Animal.all

  end

  def show
    @animal = Animal.find(params[:id])
    @animal_comment = AnimalComment.new
  end

  def new
    @animal = Animal.new
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user_id = current_user.id
    if @animal.save
    redirect_to animal_path(@animal), notice: "紹介に成功しました"
    else
    render :new
    end
  end

  def edit
    @animal = Animal.find(params[:id])
    if @animal.user != current_user
    redirect_to animals_path, alert: "不正なアクセスです"
    end
  end

  def update
    @animal = Animal.find(params[:id])
    if @animal.update(animal_params)
    redirect_to animal_path(@animal), notice: "更新に成功しました"
    else
    render :edit
    end
  end

  def destroy
    animal = Animal.find(params[:id])
    animal.destroy
    redirect_to animals_path
  end


  private

  def animal_params
    params.require(:animal).permit(:title, :body, :profile_image)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    animal = Animal.find(params[:animal_id])
    favorite = current_user.favorites.new(animal_id: animal.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    animal = Animal.find(params[:animal_id])
    favorite = current_user.favorites.find_by(animal_id: animal.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :authenticate_user!

  def search
  @range = params[:range]

    if @range == "User"
      @users = User.looks(params[:search], params[:word])
    else
      @animals = Animal.looks(params[:search], params[:word])
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @animal = Animal.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to users_path, alert: "不正なアクセスです"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
    redirect_to user_path(@user), notice: "更新に成功しました"
    else
    render :edit
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image)
  end

end

app/helpers/animal_comments_helper.rb
module AnimalCommentsHelper
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Animalnav</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

   <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
     <% if flash[:notice] %>
    <div class="alert alert-info">
      <p class="notice"><%= notice %></p>
    </div>
    <% end %>

    <% if flash[:alert] %>
    <div class="alert alert-danger">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>


  <header class="shadow-sm">
    <nav class="navbar navbar-expand-lg navbar-light">
     <div class="container">
      <a class="navbar-brand p-3" href="/"><h2>Animal Nav</h2></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
            <li class="search_form">
              <%= form_with url: search_path, local: true, method: :get do |f| %>
              <%= f.text_field :word %>
              <%= f.select :range, options_for_select([['User'], ['Animal']]) %>
              <%= f.select :search, options_for_select([["完全一致","perfect_match"], ["前方一致","forward_match"],  ["後方一致","backward_match"], ["部分一致","partial_match"]]) %>
              <%= f.submit "検索する", class: "btn btn-danger" %>
            </li>
            <% end %>
            <li class="nav-item">
             <%= link_to  user_path(current_user), class: 'btn btn-outline-danger  mr-2' do %>
            <i class="fas fa-user"></i> MyPege<% end %>
            </li>

            <li class="nav-item">
              <%= link_to  users_path, class: 'btn btn-outline-danger  mr-2' do %>
            <i class="fas fa-users"></i> Navigator一覧<% end %>
            </li>
            <li class="nav-item">
              <%= link_to  animals_path, class: 'btn btn-outline-danger  mr-2' do %>
            <i class="fas fa-feather-alt"></i> Pet一覧<% end %>
            </li>
             <li class="nav-item">
              <%= link_to  new_animal_path, class: 'btn btn-outline-danger  mr-2' do %>
            <i class="fas fa-dove"></i> Pet紹介<% end %>
            </li>
              <%= link_to  destroy_user_session_path, method: :delete, class: 'btn btn-outline-danger mr-2' do %>
            <i class="fas fa-sign-out-alt"></i></i> Logout<% end %>
            </li>
            <% else %>
            <li class="nav-item">
              <%= link_to  new_user_registration_path, class: 'btn btn-outline-danger  mr-2' do %>
            <i class="fas fa-paw"></i> 新規登録<% end %>
            </li>
            <li class="nav-item">
              <%= link_to  new_user_session_path, class: 'btn btn-outline-danger mr-2' do %>
            <i class="fas fa-cat"></i> ログイン<% end %>
            </li>
            <li class="nav-item">
              <%= link_to  users_path, class: 'btn btn-outline-danger  mr-2' do %>
            <i class="fas fa-users"></i> Navigator一覧<% end %>
            </li>
              <%= link_to  animals_path, class: 'btn btn-outline-danger  mr-2' do %>
            <i class="fas fa-feather-alt"></i> Pet一覧<% end %>
            </li>
            </ul>
            <% end %>
       </div>
      </nav>
    </header>
</body>
<main class="mb-auto">
  <%= yield %>
</main>
<footer>
  <p class="p-3 bg-danger  text-center  text-white">CopyRight Animal Nav</p>
</footer>
</html>